# Generated by Django 5.2 on 2025-04-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patente", models.CharField(max_length=10, unique=True)),
                ("propietario", models.CharField(max_length=100)),
                ("marca", models.CharField(blank=True, max_length=50, null=True)),
                ("modelo", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField(auto_now_add=True)),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "auto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reparaciones",
                        to="taller.auto",
                    ),
                ),
            ],
        ),
    ]
